"""add telemetry history tables

Revision ID: 0d4ccca42831
Revises: 23a79357c81f
Create Date: 2026-07-29 01:24:48.287069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4ccca42831'
down_revision: Union[str, Sequence[str], None] = '23a79357c81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_telemetry_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('vibration_mm_s', sa.Float(), nullable=True),
    sa.Column('power_consumption_kw', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machine_telemetry_machine_recorded', 'machine_telemetry_readings', ['machine_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_readings_machine_id'), 'machine_telemetry_readings', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_readings_recorded_at'), 'machine_telemetry_readings', ['recorded_at'], unique=False)
    op.create_table('robot_telemetry_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_task', sa.String(length=250), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('utilization_percent', sa.Float(), nullable=False),
    sa.Column('battery_level_percent', sa.Float(), nullable=True),
    sa.Column('payload_kg', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_telemetry_readings_recorded_at'), 'robot_telemetry_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_robot_telemetry_readings_robot_id'), 'robot_telemetry_readings', ['robot_id'], unique=False)
    op.create_index('ix_robot_telemetry_robot_recorded', 'robot_telemetry_readings', ['robot_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_robot_telemetry_robot_recorded', table_name='robot_telemetry_readings')
    op.drop_index(op.f('ix_robot_telemetry_readings_robot_id'), table_name='robot_telemetry_readings')
    op.drop_index(op.f('ix_robot_telemetry_readings_recorded_at'), table_name='robot_telemetry_readings')
    op.drop_table('robot_telemetry_readings')
    op.drop_index(op.f('ix_machine_telemetry_readings_recorded_at'), table_name='machine_telemetry_readings')
    op.drop_index(op.f('ix_machine_telemetry_readings_machine_id'), table_name='machine_telemetry_readings')
    op.drop_index('ix_machine_telemetry_machine_recorded', table_name='machine_telemetry_readings')
    op.drop_table('machine_telemetry_readings')
    # ### end Alembic commands ###
