"""add maintenance work orders

Revision ID: 11626f4f7b3b
Revises: 0d4ccca42831
Create Date: 2026-07-29 18:55:12.250144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11626f4f7b3b'
down_revision: Union[str, Sequence[str], None] = '0d4ccca42831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_code', sa.String(length=80), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='maintenance_priority'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Scheduled', 'In Progress', 'Completed', 'Cancelled', name='maintenance_work_order_status'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=150), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_work_orders_assigned_to'), 'maintenance_work_orders', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_machine_id'), 'maintenance_work_orders', ['machine_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_priority'), 'maintenance_work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_scheduled_for'), 'maintenance_work_orders', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_status'), 'maintenance_work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_title'), 'maintenance_work_orders', ['title'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_work_order_code'), 'maintenance_work_orders', ['work_order_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_work_orders_work_order_code'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_title'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_scheduled_for'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_priority'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_machine_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_assigned_to'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    # ### end Alembic commands ###
