"""create robots table

Revision ID: 23a79357c81f
Revises: e4dd2516158b
Create Date: 2026-07-29 00:08:06.870002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a79357c81f'
down_revision: Union[str, Sequence[str], None] = 'e4dd2516158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('robot_code', sa.String(length=80), nullable=False),
    sa.Column('robot_type', sa.Enum('Articulated', 'Collaborative Robot', 'SCARA', 'Delta', 'Autonomous Mobile Robot', 'Welding Robot', 'Palletizing Robot', 'Inspection Robot', 'Other', name='robot_type'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Idle', 'Warning', 'Error', 'Offline', 'Maintenance', name='robot_status'), nullable=False),
    sa.Column('facility', sa.String(length=150), nullable=False),
    sa.Column('production_line', sa.String(length=150), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('current_task', sa.String(length=250), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('utilization_percent', sa.Float(), nullable=False),
    sa.Column('battery_level_percent', sa.Float(), nullable=True),
    sa.Column('payload_kg', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('last_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_error_code'), 'robots', ['error_code'], unique=False)
    op.create_index(op.f('ix_robots_facility'), 'robots', ['facility'], unique=False)
    op.create_index(op.f('ix_robots_last_seen_at'), 'robots', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_robots_name'), 'robots', ['name'], unique=False)
    op.create_index(op.f('ix_robots_next_maintenance_at'), 'robots', ['next_maintenance_at'], unique=False)
    op.create_index(op.f('ix_robots_robot_code'), 'robots', ['robot_code'], unique=True)
    op.create_index(op.f('ix_robots_robot_type'), 'robots', ['robot_type'], unique=False)
    op.create_index(op.f('ix_robots_status'), 'robots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robots_status'), table_name='robots')
    op.drop_index(op.f('ix_robots_robot_type'), table_name='robots')
    op.drop_index(op.f('ix_robots_robot_code'), table_name='robots')
    op.drop_index(op.f('ix_robots_next_maintenance_at'), table_name='robots')
    op.drop_index(op.f('ix_robots_name'), table_name='robots')
    op.drop_index(op.f('ix_robots_last_seen_at'), table_name='robots')
    op.drop_index(op.f('ix_robots_facility'), table_name='robots')
    op.drop_index(op.f('ix_robots_error_code'), table_name='robots')
    op.drop_table('robots')
    # ### end Alembic commands ###
