"""create vision inspections table

Revision ID: c1ac822bc0a2
Revises: e126ae31aaca
Create Date: 2026-08-03 20:25:56.565975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ac822bc0a2'
down_revision: Union[str, Sequence[str], None] = 'e126ae31aaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_code', sa.String(length=80), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('camera', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=150), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Processing', 'Completed', 'Failed', name='vision_inspection_status'), nullable=False),
    sa.Column('result', sa.Enum('Pass', 'Defect', 'Review', name='vision_inspection_result'), nullable=True),
    sa.Column('severity', sa.Enum('Low', 'Medium', 'High', 'Critical', name='vision_inspection_severity'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('defect_type', sa.String(length=150), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 100)', name='ck_vision_inspections_confidence_range'),
    sa.CheckConstraint('image_height > 0', name='ck_vision_inspections_image_height_positive'),
    sa.CheckConstraint('image_width > 0', name='ck_vision_inspections_image_width_positive'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_vision_inspections_checksum_sha256'), 'vision_inspections', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_vision_inspections_inspection_code'), 'vision_inspections', ['inspection_code'], unique=True)
    op.create_index(op.f('ix_vision_inspections_machine_id'), 'vision_inspections', ['machine_id'], unique=False)
    op.create_index(op.f('ix_vision_inspections_product_name'), 'vision_inspections', ['product_name'], unique=False)
    op.create_index(op.f('ix_vision_inspections_result'), 'vision_inspections', ['result'], unique=False)
    op.create_index(op.f('ix_vision_inspections_severity'), 'vision_inspections', ['severity'], unique=False)
    op.create_index(op.f('ix_vision_inspections_status'), 'vision_inspections', ['status'], unique=False)
    op.create_index(op.f('ix_vision_inspections_uploaded_by_user_id'), 'vision_inspections', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_vision_inspections_zone'), 'vision_inspections', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_inspections_zone'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_uploaded_by_user_id'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_status'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_severity'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_result'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_product_name'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_machine_id'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_inspection_code'), table_name='vision_inspections')
    op.drop_index(op.f('ix_vision_inspections_checksum_sha256'), table_name='vision_inspections')
    op.drop_table('vision_inspections')

    op.execute(
        "DROP TYPE IF EXISTS "
        "vision_inspection_severity"
    )
    op.execute(
        "DROP TYPE IF EXISTS "
        "vision_inspection_result"
    )
    op.execute(
        "DROP TYPE IF EXISTS "
        "vision_inspection_status"
    )
    # ### end Alembic commands ###
