"""create machines table

Revision ID: e4dd2516158b
Revises: 4fd853a4f587
Create Date: 2026-07-28 20:29:26.003906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dd2516158b'
down_revision: Union[str, Sequence[str], None] = '4fd853a4f587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_code', sa.String(length=80), nullable=False),
    sa.Column('machine_type', sa.Enum('CNC', 'Conveyor', 'Compressor', 'Pump', 'Turbine', 'Generator', 'Packaging', 'Other', name='machine_type'), nullable=False),
    sa.Column('status', sa.Enum('Operational', 'Warning', 'Critical', 'Offline', 'Maintenance', name='machine_status'), nullable=False),
    sa.Column('facility', sa.String(length=150), nullable=False),
    sa.Column('production_line', sa.String(length=150), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('vibration_mm_s', sa.Float(), nullable=True),
    sa.Column('power_consumption_kw', sa.Float(), nullable=True),
    sa.Column('last_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_asset_code'), 'machines', ['asset_code'], unique=True)
    op.create_index(op.f('ix_machines_facility'), 'machines', ['facility'], unique=False)
    op.create_index(op.f('ix_machines_last_seen_at'), 'machines', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=False)
    op.create_index(op.f('ix_machines_next_maintenance_at'), 'machines', ['next_maintenance_at'], unique=False)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_next_maintenance_at'), table_name='machines')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_index(op.f('ix_machines_last_seen_at'), table_name='machines')
    op.drop_index(op.f('ix_machines_facility'), table_name='machines')
    op.drop_index(op.f('ix_machines_asset_code'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
